name: Painting With Silver
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49928
title: Painting With Silver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a9a9a9'
    - '#848484'
    - '#3b3b3b'
    - '#cfcfcf'
  brandStrength: 0.375
  lightness: 0.8872844772413373
  saturation: 0.8162303979042917
  rhythmicContrast: 0.7473986446857452
purpose: []
